### ISSUE TITLE
ADC input values with temperature sensor?

### ISSUE THREAD

**Issue by siliconja** [Hixie/localbit#3]
Hi, I'm trying out localbit while having the the temperature sensor + LED display connected to the cloudbit.

- LED displays 75. (75 deg F temperature.)
- localbit is producing a values between 0xb7-0xb9 (183-185)
- If I turn off localbit and run `/usr/local/lb/ADC/bin/getADC -1` (in conjunction with `/usr/local/lb/ADC/bin/ADC.d`), I'm seeing values between 190-192.

The only sense I can make of these numbers (guessing here) is that 75 F = 23.8889 C, and 24 * 8 = 192.

Any ideas on accurate temperature readings?

**Comment by Hixie** [comment]
Hey sorry I just saw this. I'm afraid I forget exactly how the numbers work out for the thermometer bit. Did you ever figure it out?

**Comment by siliconja** [comment]
The guess regarding the temp conversions seemed to work for me at the time. I also have moved on and don't have my localbit set up / running right now.

**Comment by Hixie** [comment]
Cool. Thanks for the update!
